# Generated by Django 4.0 on 2021-12-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('suite', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=8)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('catchPhrase', models.CharField(max_length=200)),
                ('company_bs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
