# Generated by Django 4.0 on 2021-12-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='catchPhrase',
            new_name='catch_phrase',
        ),
    ]
